FROM java:8-jre
MAINTAINER HZC baiyun <GeminiAngels@163.com>

ADD ./jar/hzc-auth.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=hzc-auth", "-Dpinpoint.applicationName=AUTH", "-jar", "/app/hzc-auth.jar"]
