FROM java:8-jre
MAINTAINER HZC baiyun <GeminiAngels@163.com>

ADD ./jar/hzc-gateway.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=hzc-gateway", "-Dpinpoint.applicationName=GATEWAY", "-jar", "/app/hzc-gateway.jar"]

EXPOSE 9999